### ISSUE TITLE
The camera does not start

### ISSUE THREAD

**Issue by Mirsaid02** [MSM8226-Samsung/android_kernel_samsung_ms013g#2]
01-04 20:42:36.390 249 774 E mm-camera-intf: mm_camera_open: opened, break out while loop
01-04 20:42:36.390 249 774 E mm-camera-intf: mm_camera_open: cannot open control fd of '/dev/video2' (Connection timed out)
01-04 20:42:36.390 249 774 E mm-camera-intf: mm_camera_socket_create: socket_fd =17
01-04 20:42:36.390 249 774 E mm-camera-intf: mm_camera_socket_create: value of rc=-1
01-04 20:42:36.390 249 774 E mm-camera-intf: mm_camera_socket_create: socket_fd=-1 No such file or directory
01-04 20:42:36.412 249 774 E mm-camera-intf: mm_camera_socket_create: socket_fd =17
01-04 20:42:36.412 249 774 E mm-camera-intf: mm_camera_socket_create: value of rc=-1
01-04 20:42:36.412 249 774 E mm-camera-intf: mm_camera_socket_create: socket_fd=-1 No such file or directory
01-04 20:42:36.412 249 774 E mm-camera-intf: mm_camera_open: cannot open domain socket fd of '/dev/video2'(No such file or directory)
01-04 20:42:36.412 249 774 E mm-camera-intf: camera_open: mm_camera_open err = -1
01-04 20:42:36.412 249 774 E QCamera2HWI: initCapabilities: camera_open failed
01-04 20:42:36.412 249 774 W QCamera2HWI: getCapabilities : __dbg: init capabilities rc = -2147483648, :0
01-04 20:42:36.412 249 774 E QCamera2Factory: [getCameraInfo] __dbg: getCapabilities failed
01-04 20:42:36.412 249 774 W QCamera2Factory: getCameraInfo: X
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: Exception while creating CameraDeviceInfo
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: java.lang.RuntimeException: Fail to get camera info
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.hardware.Camera._getCameraInfo(Native Method)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.hardware.Camera.getCameraInfo(Camera.java:244)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at com.android.ex.camera2.portability.AndroidCameraAgentImpl$AndroidCameraDeviceInfo.create(AndroidCameraAgentImpl.java:151)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at com.android.ex.camera2.portability.AndroidCameraAgentImpl.getCameraDeviceInfo(AndroidCameraAgentImpl.java:99)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at com.android.camera.app.CameraController.(CameraController.java:93)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1480)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.app.Activity.performCreate(Activity.java:6237)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.os.Handler.dispatchMessage(Handler.java:102)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.os.Looper.loop(Looper.java:148)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at android.app.ActivityThread.main(ActivityThread.java:5466)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at java.lang.reflect.Method.invoke(Native Method)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-04 20:42:36.417 4286 4286 E CAM2PORT_AndCamAgntImp: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-04 20:42:36.417 4286 4286 W CAM_CameraActivity: Camera open failure: GETTING_CAMERA_INFO
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: Handling Camera Open Failure:
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: java.lang.Exception
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at com.android.camera.FatalErrorHandlerImpl.onCameraOpenFailure(FatalErrorHandlerImpl.java:52)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at com.android.camera.CameraActivity.onDeviceOpenFailure(CameraActivity.java:553)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at com.android.camera.app.CameraController.(CameraController.java:95)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1480)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.app.Activity.performCreate(Activity.java:6237)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.os.Handler.dispatchMessage(Handler.java:102)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.os.Looper.loop(Looper.java:148)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at android.app.ActivityThread.main(ActivityThread.java:5466)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at java.lang.reflect.Method.invoke(Native Method)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-04 20:42:36.418 4286 4286 E CAM_FatalErrorHandler: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-04 20:42:36.423 249 1151 W QCamera2Factory: getCameraInfo: E, camera_id = 0
#01-04 20:42:36.423 249 1151 E mm-camera-intf: mm_camera_open: begin

How can I fix it?

**Comment by aapav01** [comment]
which branch cm-12.1 or cm-13.0 cm-11.0

**Comment by Mirsaid02** [comment]
cm-13.0

**Comment by Mirsaid02** [comment]
And can I take part in yours with Mukul Soni development with CyanogenMod 13.0? I built my own ROM :) I'll be very happy. I can attract help of members of the forum from site 4pda.ru.

**Comment by aapav01** [comment]
you can join this org but not the @mukulsoni 's one as he have his own tree :+1:
